[platformio]
# Tell PlatformIO to compile source files in this directory directly
src_dir = .
# Arduino Uno is the active board
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM5
upload_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM5
upload_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
